language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- npm run build
- npm run test
- npm run cover
env:
  global:
    secure: cikCRrMbZWNSC4mu1G2GrY9+QF1KXFi/BgVrVRwu5XJOGGI8zc5KNd80c2MqSIvO5WTV9WTsrWoIbxOOn+NFLu6YUR11zy5bd3AXLxv35y1LcvvOFgzRo1Jl6OZjYjP3826kBDH47lVsilZhKx5FPl2tbTYEPpPAAnjq1JcPra/b8BKXlVJdyw4gU5mMx+zj+FQAitATO+8r2+WkHb7Mlu0MggtXmkIXeccOcnQi/XKj82YaArdfeqzDsbodxwH3QrBxrP+J4d6NbF/7Hp9n17hUwt0piLtJVeMbS7b34Zti1/m67HbnMWEe8lW6h1Q8qPptQSpuraiPMHtznpDAcVUcxampaGsfrfpJsflEUzKG5Pq95dRo4VeyfT7u6ZPEPBnevdmFDtvyzbXVOmgbsrMi5Ib5JA1himSWfRhJkTnwIEgNSHfK4gVqi+iJWjzobDn7or2sso/zbp1YGIEXnJRLNpNTyqoE9o6zudICyivZgPqgNo0cxMxgQf94wDaEbKlg3Itj0gM2cwNTSBnNLNpkZdS16S2d4YO/bdARFVootmoUZvYDovif8GuxJWQY7nKF+ljX+rUhUhHeO2U2GzkO597LyFzmNnG8IIfpeiD+pFMR1yo4k3VBtInbCfrCBRMNBkC8tG4uK2kGGrvqto9+0v8E0KsWapHpcVtFwdk=
